version: '3.1'

services:
  nest:
    build: .
    volumes:
      - "./src:/app/src"
    ports:
      - '3000:3000'
    depends_on:
      - mongo


  mongo:
    image: 'mongo:latest'
    volumes:
      - mongodata:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

volumes:
  mongodata:
